apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    type: elasticsearch
spec:
  storageClassName: standard
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"